<?php

/*
Theme Name: Latino Theatre Projects Theme
Author: Latino Theatre Projects Design/Development Team
Author URI: www.annaksabo.com
Description: Theme for the Latino Theatre Projects website
*/

//all of this is generated by wordpress to supports widgets

// Register the nav menu
register_nav_menus(array(
    'main-menu' => __('Main'),
));

//register the sidebar
register_sidebar( array(
    'before_widget' => '<li id="%1$s" class="widget %2$s">',
	'after_widget'  => '</li>',
	'before_title'  => '<h2>',
	'after_title'   => '</h2>' 
));

// Support for themes
add_theme_support('post-thumbnails');

// Support for excerpts
add_post_type_support('page', 'excerpt');

//title tag
function get_my_title_tag () {
    
	global $post;
    
	if (is_front_page()){
		bloginfo('description');
	} 
	elseif (is_page() || is_single()){
		the_title();
	}
	else {	
		bloginfo('description');
	}
    
	if ($post->post_parent){
		echo ' | ';
		echo get_the_title($post->post_parent);
	}
    
	echo ' | ';
	bloginfo('name');
	echo ' | ';
	echo 'Seattle, WA.';
}

?>